import { Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"

const nunito = Nunito({
  subsets: ["latin", "cyrillic"],
});

export const metadata = {
  title: "WorkNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased w-full h-full min-h-screen`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
